### ISSUE TITLE
Error 500 when trying to run a task with shovel-server

### ISSUE THREAD

**Issue by tsileo** [seomoz/shovel#5]
Hello,

When I run shovel-server, I got an error 500 when I try to run a task and I got this in the debug:

```
Traceback (most recent call last):
  File "/home/topica/virtualenvs/tonality-prod/bin/bottle.py", line 737, in _handle
    return route.call(**args)
  File "/home/topica/virtualenvs/tonality-prod/bin/bottle.py", line 1456, in wrapper
    rv = callback(*a, **ka)
  File "/home/topica/virtualenvs/tonality-prod/bin/shovel-server", line 114, in _task
    pkgutil.get_data('shovel', 'templates/results.tpl'),
  File "/usr/lib/python2.7/pkgutil.py", line 583, in get_data
    return loader.get_data(resource_name)
  File "/usr/lib/python2.7/pkgutil.py", line 247, in get_data
    return open(pathname, "rb").read()
    IOError: [Errno 2] No such file or directory: './templates/results.tpl'
```

Any idea why ?

**Comment by b4hand** [comment]
Closing this out as well since shovel-server is not part of shovel anymore.
